# Generated by Django 3.0.7 on 2020-09-22 13:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_post_image'),
    ]

    operations = [
        migrations.CreateModel(
            name='FirstPageNews',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('quote', models.TextField()),
                ('image', models.ImageField(default='default-image.png', upload_to='first_page_pics')),
            ],
        ),
    ]
