# Generated by Django 3.0.7 on 2020-09-23 15:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0003_firstpagenews'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='FirstPageNews',
            new_name='FirstPageQuotes',
        ),
    ]
